---
- name: Create user accounts
  user:
    name: "{{ item }}"
    groups: sudo,www-data
  with_items: "{{ users }}"
  tags: user

- name: Add authorized keys
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', './keys/'+ item +'.txt') }}"  
  with_items: "{{ users }}" 
  tags: user          

- name: Allow admin users to sudo without a password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%admin'
    line: '%admin ALL=(ALL) NOPASSWD: ALL'
  tags: user
